# profil-unabhängige Properties
server:
  port: ${HTTP_PORT:8080}
spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
